name: Update Network

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      chainid:
        description: 'Chain ID'
        required: true
        type: string
      explorer:
        description: 'Explorer'
        required: true
        type: string
      multicall:
        description: 'Multicall'
        required: true
        type: string
      start:
        description: 'Start'
        required: true
        type: string
      logo:
        description: 'Logo (ipfs hash)'
        required: true
        type: string
      networkname:
        description: 'Network Name'
        required: true
        type: string
      shortname:
        description: 'Short Name'
        required: true
        type: string
      testnet:
        description: 'Testnet (true/false)'
        required: false
        default: ''
        type: string
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '16.10.0'
      - name: Add new network
        run: |
          node scripts/addNetwork.ts ${{ inputs.chainid }} ${{ inputs.explorer }} ${{ inputs.multicall }} ${{ inputs.start }} ${{ inputs.logo }} "${{ inputs.networkname }}" ${{ inputs.shortname }} ${{ inputs.testnet }}
      - name: Update minor
        run: |
          npm --no-git-tag-version version patch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            commit-message: Add new network ${{ inputs.networkName }} - ${{ inputs.chainid }}
            title: Add new network ${{ inputs.networkName }} - ${{ inputs.chainid }}
            body: |
              - src/networks.json updated
  
              Auto-generated by Github Actions
            branch: new-network-${{ inputs.chainid }}
